#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDDEMPRESA")]
	public partial class DCEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_capacitacion(tbl_capacitacion instance);
    partial void Updatetbl_capacitacion(tbl_capacitacion instance);
    partial void Deletetbl_capacitacion(tbl_capacitacion instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    partial void Inserttbl_cargo(tbl_cargo instance);
    partial void Updatetbl_cargo(tbl_cargo instance);
    partial void Deletetbl_cargo(tbl_cargo instance);
    partial void Inserttbl_departamento(tbl_departamento instance);
    partial void Updatetbl_departamento(tbl_departamento instance);
    partial void Deletetbl_departamento(tbl_departamento instance);
    partial void Inserttbl_empleado(tbl_empleado instance);
    partial void Updatetbl_empleado(tbl_empleado instance);
    partial void Deletetbl_empleado(tbl_empleado instance);
    partial void Inserttbl_empresa(tbl_empresa instance);
    partial void Updatetbl_empresa(tbl_empresa instance);
    partial void Deletetbl_empresa(tbl_empresa instance);
    partial void Inserttbl_familiar(tbl_familiar instance);
    partial void Updatetbl_familiar(tbl_familiar instance);
    partial void Deletetbl_familiar(tbl_familiar instance);
    partial void Inserttbl_referencia(tbl_referencia instance);
    partial void Updatetbl_referencia(tbl_referencia instance);
    partial void Deletetbl_referencia(tbl_referencia instance);
    partial void Inserttbl_rol(tbl_rol instance);
    partial void Updatetbl_rol(tbl_rol instance);
    partial void Deletetbl_rol(tbl_rol instance);
    #endregion
		
		public DCEmpresaDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.BDDEMPRESAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_capacitacion> tbl_capacitacions
		{
			get
			{
				return this.GetTable<tbl_capacitacion>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuarios
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_cargo> tbl_cargos
		{
			get
			{
				return this.GetTable<tbl_cargo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_departamento> tbl_departamentos
		{
			get
			{
				return this.GetTable<tbl_departamento>();
			}
		}
		
		public System.Data.Linq.Table<tbl_empleado> tbl_empleados
		{
			get
			{
				return this.GetTable<tbl_empleado>();
			}
		}
		
		public System.Data.Linq.Table<tbl_empresa> tbl_empresas
		{
			get
			{
				return this.GetTable<tbl_empresa>();
			}
		}
		
		public System.Data.Linq.Table<tbl_familiar> tbl_familiars
		{
			get
			{
				return this.GetTable<tbl_familiar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_referencia> tbl_referencias
		{
			get
			{
				return this.GetTable<tbl_referencia>();
			}
		}
		
		public System.Data.Linq.Table<tbl_rol> tbl_rols
		{
			get
			{
				return this.GetTable<tbl_rol>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_capacitacion")]
	public partial class tbl_capacitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_capacitacion;
		
		private string _descripcion_capacitacion;
		
		private System.DateTime _fecha_capacitacion;
		
		private char _estado_capacitacion;
		
		private System.Nullable<int> _id_empleado;
		
		private EntityRef<tbl_empleado> _tbl_empleado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_capacitacionChanging(int value);
    partial void Onid_capacitacionChanged();
    partial void Ondescripcion_capacitacionChanging(string value);
    partial void Ondescripcion_capacitacionChanged();
    partial void Onfecha_capacitacionChanging(System.DateTime value);
    partial void Onfecha_capacitacionChanged();
    partial void Onestado_capacitacionChanging(char value);
    partial void Onestado_capacitacionChanged();
    partial void Onid_empleadoChanging(System.Nullable<int> value);
    partial void Onid_empleadoChanged();
    #endregion
		
		public tbl_capacitacion()
		{
			this._tbl_empleado = default(EntityRef<tbl_empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_capacitacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_capacitacion
		{
			get
			{
				return this._id_capacitacion;
			}
			set
			{
				if ((this._id_capacitacion != value))
				{
					this.Onid_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._id_capacitacion = value;
					this.SendPropertyChanged("id_capacitacion");
					this.Onid_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_capacitacion", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_capacitacion
		{
			get
			{
				return this._descripcion_capacitacion;
			}
			set
			{
				if ((this._descripcion_capacitacion != value))
				{
					this.Ondescripcion_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._descripcion_capacitacion = value;
					this.SendPropertyChanged("descripcion_capacitacion");
					this.Ondescripcion_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_capacitacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_capacitacion
		{
			get
			{
				return this._fecha_capacitacion;
			}
			set
			{
				if ((this._fecha_capacitacion != value))
				{
					this.Onfecha_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._fecha_capacitacion = value;
					this.SendPropertyChanged("fecha_capacitacion");
					this.Onfecha_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_capacitacion", DbType="Char(1) NOT NULL")]
		public char estado_capacitacion
		{
			get
			{
				return this._estado_capacitacion;
			}
			set
			{
				if ((this._estado_capacitacion != value))
				{
					this.Onestado_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._estado_capacitacion = value;
					this.SendPropertyChanged("estado_capacitacion");
					this.Onestado_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="Int")]
		public System.Nullable<int> id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					if (this._tbl_empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_capacitacion", Storage="_tbl_empleado", ThisKey="id_empleado", OtherKey="id_empleado", IsForeignKey=true)]
		public tbl_empleado tbl_empleado
		{
			get
			{
				return this._tbl_empleado.Entity;
			}
			set
			{
				tbl_empleado previousValue = this._tbl_empleado.Entity;
				if (((previousValue != value) 
							|| (this._tbl_empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_empleado.Entity = null;
						previousValue.tbl_capacitacions.Remove(this);
					}
					this._tbl_empleado.Entity = value;
					if ((value != null))
					{
						value.tbl_capacitacions.Add(this);
						this._id_empleado = value.id_empleado;
					}
					else
					{
						this._id_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombres_usuario;
		
		private string _dni_usuario;
		
		private string _email_usuario;
		
		private string _pass_usuario;
		
		private System.DateTime _fecha_usuario;
		
		private char _estado_usuario;
		
		private System.Nullable<int> _id_rol;
		
		private EntityRef<tbl_rol> _tbl_rol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnombres_usuarioChanging(string value);
    partial void Onnombres_usuarioChanged();
    partial void Ondni_usuarioChanging(string value);
    partial void Ondni_usuarioChanged();
    partial void Onemail_usuarioChanging(string value);
    partial void Onemail_usuarioChanged();
    partial void Onpass_usuarioChanging(string value);
    partial void Onpass_usuarioChanged();
    partial void Onfecha_usuarioChanging(System.DateTime value);
    partial void Onfecha_usuarioChanged();
    partial void Onestado_usuarioChanging(char value);
    partial void Onestado_usuarioChanged();
    partial void Onid_rolChanging(System.Nullable<int> value);
    partial void Onid_rolChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_rol = default(EntityRef<tbl_rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_usuario
		{
			get
			{
				return this._nombres_usuario;
			}
			set
			{
				if ((this._nombres_usuario != value))
				{
					this.Onnombres_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombres_usuario = value;
					this.SendPropertyChanged("nombres_usuario");
					this.Onnombres_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_usuario", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string dni_usuario
		{
			get
			{
				return this._dni_usuario;
			}
			set
			{
				if ((this._dni_usuario != value))
				{
					this.Ondni_usuarioChanging(value);
					this.SendPropertyChanging();
					this._dni_usuario = value;
					this.SendPropertyChanged("dni_usuario");
					this.Ondni_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email_usuario
		{
			get
			{
				return this._email_usuario;
			}
			set
			{
				if ((this._email_usuario != value))
				{
					this.Onemail_usuarioChanging(value);
					this.SendPropertyChanging();
					this._email_usuario = value;
					this.SendPropertyChanged("email_usuario");
					this.Onemail_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_usuario", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string pass_usuario
		{
			get
			{
				return this._pass_usuario;
			}
			set
			{
				if ((this._pass_usuario != value))
				{
					this.Onpass_usuarioChanging(value);
					this.SendPropertyChanging();
					this._pass_usuario = value;
					this.SendPropertyChanged("pass_usuario");
					this.Onpass_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_usuario", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_usuario
		{
			get
			{
				return this._fecha_usuario;
			}
			set
			{
				if ((this._fecha_usuario != value))
				{
					this.Onfecha_usuarioChanging(value);
					this.SendPropertyChanging();
					this._fecha_usuario = value;
					this.SendPropertyChanged("fecha_usuario");
					this.Onfecha_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_usuario", DbType="Char(1) NOT NULL")]
		public char estado_usuario
		{
			get
			{
				return this._estado_usuario;
			}
			set
			{
				if ((this._estado_usuario != value))
				{
					this.Onestado_usuarioChanging(value);
					this.SendPropertyChanging();
					this._estado_usuario = value;
					this.SendPropertyChanged("estado_usuario");
					this.Onestado_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", DbType="Int")]
		public System.Nullable<int> id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					if (this._tbl_rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_rol", ThisKey="id_rol", OtherKey="id_rol", IsForeignKey=true)]
		public tbl_rol tbl_rol
		{
			get
			{
				return this._tbl_rol.Entity;
			}
			set
			{
				tbl_rol previousValue = this._tbl_rol.Entity;
				if (((previousValue != value) 
							|| (this._tbl_rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_rol.Entity = null;
						previousValue.tbl_usuarios.Remove(this);
					}
					this._tbl_rol.Entity = value;
					if ((value != null))
					{
						value.tbl_usuarios.Add(this);
						this._id_rol = value.id_rol;
					}
					else
					{
						this._id_rol = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cargos")]
	public partial class tbl_cargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cargos;
		
		private string _descripcion_cargos;
		
		private System.DateTime _fecha_cargos;
		
		private char _estado_cargos;
		
		private EntitySet<tbl_empleado> _tbl_empleados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cargosChanging(int value);
    partial void Onid_cargosChanged();
    partial void Ondescripcion_cargosChanging(string value);
    partial void Ondescripcion_cargosChanged();
    partial void Onfecha_cargosChanging(System.DateTime value);
    partial void Onfecha_cargosChanged();
    partial void Onestado_cargosChanging(char value);
    partial void Onestado_cargosChanged();
    #endregion
		
		public tbl_cargo()
		{
			this._tbl_empleados = new EntitySet<tbl_empleado>(new Action<tbl_empleado>(this.attach_tbl_empleados), new Action<tbl_empleado>(this.detach_tbl_empleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cargos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cargos
		{
			get
			{
				return this._id_cargos;
			}
			set
			{
				if ((this._id_cargos != value))
				{
					this.Onid_cargosChanging(value);
					this.SendPropertyChanging();
					this._id_cargos = value;
					this.SendPropertyChanged("id_cargos");
					this.Onid_cargosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_cargos", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_cargos
		{
			get
			{
				return this._descripcion_cargos;
			}
			set
			{
				if ((this._descripcion_cargos != value))
				{
					this.Ondescripcion_cargosChanging(value);
					this.SendPropertyChanging();
					this._descripcion_cargos = value;
					this.SendPropertyChanged("descripcion_cargos");
					this.Ondescripcion_cargosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_cargos", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_cargos
		{
			get
			{
				return this._fecha_cargos;
			}
			set
			{
				if ((this._fecha_cargos != value))
				{
					this.Onfecha_cargosChanging(value);
					this.SendPropertyChanging();
					this._fecha_cargos = value;
					this.SendPropertyChanged("fecha_cargos");
					this.Onfecha_cargosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_cargos", DbType="Char(1) NOT NULL")]
		public char estado_cargos
		{
			get
			{
				return this._estado_cargos;
			}
			set
			{
				if ((this._estado_cargos != value))
				{
					this.Onestado_cargosChanging(value);
					this.SendPropertyChanging();
					this._estado_cargos = value;
					this.SendPropertyChanged("estado_cargos");
					this.Onestado_cargosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_cargo_tbl_empleado", Storage="_tbl_empleados", ThisKey="id_cargos", OtherKey="id_cargos")]
		public EntitySet<tbl_empleado> tbl_empleados
		{
			get
			{
				return this._tbl_empleados;
			}
			set
			{
				this._tbl_empleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_empleados(tbl_empleado entity)
		{
			this.SendPropertyChanging();
			entity.tbl_cargo = this;
		}
		
		private void detach_tbl_empleados(tbl_empleado entity)
		{
			this.SendPropertyChanging();
			entity.tbl_cargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_departamento")]
	public partial class tbl_departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_departamento;
		
		private string _descripcion_departamento;
		
		private System.DateTime _fecha_departamento;
		
		private char _estado_departamento;
		
		private System.Nullable<int> _id_empresa;
		
		private EntitySet<tbl_empleado> _tbl_empleados;
		
		private EntityRef<tbl_empresa> _tbl_empresa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_departamentoChanging(int value);
    partial void Onid_departamentoChanged();
    partial void Ondescripcion_departamentoChanging(string value);
    partial void Ondescripcion_departamentoChanged();
    partial void Onfecha_departamentoChanging(System.DateTime value);
    partial void Onfecha_departamentoChanged();
    partial void Onestado_departamentoChanging(char value);
    partial void Onestado_departamentoChanged();
    partial void Onid_empresaChanging(System.Nullable<int> value);
    partial void Onid_empresaChanged();
    #endregion
		
		public tbl_departamento()
		{
			this._tbl_empleados = new EntitySet<tbl_empleado>(new Action<tbl_empleado>(this.attach_tbl_empleados), new Action<tbl_empleado>(this.detach_tbl_empleados));
			this._tbl_empresa = default(EntityRef<tbl_empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_departamento", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_departamento
		{
			get
			{
				return this._descripcion_departamento;
			}
			set
			{
				if ((this._descripcion_departamento != value))
				{
					this.Ondescripcion_departamentoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_departamento = value;
					this.SendPropertyChanged("descripcion_departamento");
					this.Ondescripcion_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_departamento", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_departamento
		{
			get
			{
				return this._fecha_departamento;
			}
			set
			{
				if ((this._fecha_departamento != value))
				{
					this.Onfecha_departamentoChanging(value);
					this.SendPropertyChanging();
					this._fecha_departamento = value;
					this.SendPropertyChanged("fecha_departamento");
					this.Onfecha_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_departamento", DbType="Char(1) NOT NULL")]
		public char estado_departamento
		{
			get
			{
				return this._estado_departamento;
			}
			set
			{
				if ((this._estado_departamento != value))
				{
					this.Onestado_departamentoChanging(value);
					this.SendPropertyChanging();
					this._estado_departamento = value;
					this.SendPropertyChanged("estado_departamento");
					this.Onestado_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", DbType="Int")]
		public System.Nullable<int> id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					if (this._tbl_empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_empresaChanging(value);
					this.SendPropertyChanging();
					this._id_empresa = value;
					this.SendPropertyChanged("id_empresa");
					this.Onid_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_departamento_tbl_empleado", Storage="_tbl_empleados", ThisKey="id_departamento", OtherKey="id_departamento")]
		public EntitySet<tbl_empleado> tbl_empleados
		{
			get
			{
				return this._tbl_empleados;
			}
			set
			{
				this._tbl_empleados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empresa_tbl_departamento", Storage="_tbl_empresa", ThisKey="id_empresa", OtherKey="id_empresa", IsForeignKey=true)]
		public tbl_empresa tbl_empresa
		{
			get
			{
				return this._tbl_empresa.Entity;
			}
			set
			{
				tbl_empresa previousValue = this._tbl_empresa.Entity;
				if (((previousValue != value) 
							|| (this._tbl_empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_empresa.Entity = null;
						previousValue.tbl_departamentos.Remove(this);
					}
					this._tbl_empresa.Entity = value;
					if ((value != null))
					{
						value.tbl_departamentos.Add(this);
						this._id_empresa = value.id_empresa;
					}
					else
					{
						this._id_empresa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_empleados(tbl_empleado entity)
		{
			this.SendPropertyChanging();
			entity.tbl_departamento = this;
		}
		
		private void detach_tbl_empleados(tbl_empleado entity)
		{
			this.SendPropertyChanging();
			entity.tbl_departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_empleado")]
	public partial class tbl_empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empleado;
		
		private string _nombres_empleado;
		
		private string _dni_empleado;
		
		private string _direccion_empleado;
		
		private string _telefono_empleado;
		
		private string _email_empleado;
		
		private System.DateTime _fechanac_empleado;
		
		private string _foto_empleado;
		
		private System.DateTime _fecha_empleado;
		
		private char _estado_empleado;
		
		private System.Nullable<int> _id_departamento;
		
		private System.Nullable<int> _id_cargos;
		
		private EntitySet<tbl_capacitacion> _tbl_capacitacions;
		
		private EntitySet<tbl_familiar> _tbl_familiars;
		
		private EntitySet<tbl_referencia> _tbl_referencias;
		
		private EntityRef<tbl_departamento> _tbl_departamento;
		
		private EntityRef<tbl_cargo> _tbl_cargo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empleadoChanging(int value);
    partial void Onid_empleadoChanged();
    partial void Onnombres_empleadoChanging(string value);
    partial void Onnombres_empleadoChanged();
    partial void Ondni_empleadoChanging(string value);
    partial void Ondni_empleadoChanged();
    partial void Ondireccion_empleadoChanging(string value);
    partial void Ondireccion_empleadoChanged();
    partial void Ontelefono_empleadoChanging(string value);
    partial void Ontelefono_empleadoChanged();
    partial void Onemail_empleadoChanging(string value);
    partial void Onemail_empleadoChanged();
    partial void Onfechanac_empleadoChanging(System.DateTime value);
    partial void Onfechanac_empleadoChanged();
    partial void Onfoto_empleadoChanging(string value);
    partial void Onfoto_empleadoChanged();
    partial void Onfecha_empleadoChanging(System.DateTime value);
    partial void Onfecha_empleadoChanged();
    partial void Onestado_empleadoChanging(char value);
    partial void Onestado_empleadoChanged();
    partial void Onid_departamentoChanging(System.Nullable<int> value);
    partial void Onid_departamentoChanged();
    partial void Onid_cargosChanging(System.Nullable<int> value);
    partial void Onid_cargosChanged();
    #endregion
		
		public tbl_empleado()
		{
			this._tbl_capacitacions = new EntitySet<tbl_capacitacion>(new Action<tbl_capacitacion>(this.attach_tbl_capacitacions), new Action<tbl_capacitacion>(this.detach_tbl_capacitacions));
			this._tbl_familiars = new EntitySet<tbl_familiar>(new Action<tbl_familiar>(this.attach_tbl_familiars), new Action<tbl_familiar>(this.detach_tbl_familiars));
			this._tbl_referencias = new EntitySet<tbl_referencia>(new Action<tbl_referencia>(this.attach_tbl_referencias), new Action<tbl_referencia>(this.detach_tbl_referencias));
			this._tbl_departamento = default(EntityRef<tbl_departamento>);
			this._tbl_cargo = default(EntityRef<tbl_cargo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_empleado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_empleado
		{
			get
			{
				return this._nombres_empleado;
			}
			set
			{
				if ((this._nombres_empleado != value))
				{
					this.Onnombres_empleadoChanging(value);
					this.SendPropertyChanging();
					this._nombres_empleado = value;
					this.SendPropertyChanged("nombres_empleado");
					this.Onnombres_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_empleado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string dni_empleado
		{
			get
			{
				return this._dni_empleado;
			}
			set
			{
				if ((this._dni_empleado != value))
				{
					this.Ondni_empleadoChanging(value);
					this.SendPropertyChanging();
					this._dni_empleado = value;
					this.SendPropertyChanged("dni_empleado");
					this.Ondni_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_empleado", DbType="VarChar(100)")]
		public string direccion_empleado
		{
			get
			{
				return this._direccion_empleado;
			}
			set
			{
				if ((this._direccion_empleado != value))
				{
					this.Ondireccion_empleadoChanging(value);
					this.SendPropertyChanging();
					this._direccion_empleado = value;
					this.SendPropertyChanged("direccion_empleado");
					this.Ondireccion_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_empleado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefono_empleado
		{
			get
			{
				return this._telefono_empleado;
			}
			set
			{
				if ((this._telefono_empleado != value))
				{
					this.Ontelefono_empleadoChanging(value);
					this.SendPropertyChanging();
					this._telefono_empleado = value;
					this.SendPropertyChanged("telefono_empleado");
					this.Ontelefono_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_empleado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email_empleado
		{
			get
			{
				return this._email_empleado;
			}
			set
			{
				if ((this._email_empleado != value))
				{
					this.Onemail_empleadoChanging(value);
					this.SendPropertyChanging();
					this._email_empleado = value;
					this.SendPropertyChanged("email_empleado");
					this.Onemail_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechanac_empleado", DbType="Date NOT NULL")]
		public System.DateTime fechanac_empleado
		{
			get
			{
				return this._fechanac_empleado;
			}
			set
			{
				if ((this._fechanac_empleado != value))
				{
					this.Onfechanac_empleadoChanging(value);
					this.SendPropertyChanging();
					this._fechanac_empleado = value;
					this.SendPropertyChanged("fechanac_empleado");
					this.Onfechanac_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_empleado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string foto_empleado
		{
			get
			{
				return this._foto_empleado;
			}
			set
			{
				if ((this._foto_empleado != value))
				{
					this.Onfoto_empleadoChanging(value);
					this.SendPropertyChanging();
					this._foto_empleado = value;
					this.SendPropertyChanged("foto_empleado");
					this.Onfoto_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_empleado", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_empleado
		{
			get
			{
				return this._fecha_empleado;
			}
			set
			{
				if ((this._fecha_empleado != value))
				{
					this.Onfecha_empleadoChanging(value);
					this.SendPropertyChanging();
					this._fecha_empleado = value;
					this.SendPropertyChanged("fecha_empleado");
					this.Onfecha_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_empleado", DbType="Char(1) NOT NULL")]
		public char estado_empleado
		{
			get
			{
				return this._estado_empleado;
			}
			set
			{
				if ((this._estado_empleado != value))
				{
					this.Onestado_empleadoChanging(value);
					this.SendPropertyChanging();
					this._estado_empleado = value;
					this.SendPropertyChanged("estado_empleado");
					this.Onestado_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_departamento", DbType="Int")]
		public System.Nullable<int> id_departamento
		{
			get
			{
				return this._id_departamento;
			}
			set
			{
				if ((this._id_departamento != value))
				{
					if (this._tbl_departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_departamentoChanging(value);
					this.SendPropertyChanging();
					this._id_departamento = value;
					this.SendPropertyChanged("id_departamento");
					this.Onid_departamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cargos", DbType="Int")]
		public System.Nullable<int> id_cargos
		{
			get
			{
				return this._id_cargos;
			}
			set
			{
				if ((this._id_cargos != value))
				{
					if (this._tbl_cargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cargosChanging(value);
					this.SendPropertyChanging();
					this._id_cargos = value;
					this.SendPropertyChanged("id_cargos");
					this.Onid_cargosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_capacitacion", Storage="_tbl_capacitacions", ThisKey="id_empleado", OtherKey="id_empleado")]
		public EntitySet<tbl_capacitacion> tbl_capacitacions
		{
			get
			{
				return this._tbl_capacitacions;
			}
			set
			{
				this._tbl_capacitacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_familiar", Storage="_tbl_familiars", ThisKey="id_empleado", OtherKey="id_empleado")]
		public EntitySet<tbl_familiar> tbl_familiars
		{
			get
			{
				return this._tbl_familiars;
			}
			set
			{
				this._tbl_familiars.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_referencia", Storage="_tbl_referencias", ThisKey="id_empleado", OtherKey="id_empleado")]
		public EntitySet<tbl_referencia> tbl_referencias
		{
			get
			{
				return this._tbl_referencias;
			}
			set
			{
				this._tbl_referencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_departamento_tbl_empleado", Storage="_tbl_departamento", ThisKey="id_departamento", OtherKey="id_departamento", IsForeignKey=true)]
		public tbl_departamento tbl_departamento
		{
			get
			{
				return this._tbl_departamento.Entity;
			}
			set
			{
				tbl_departamento previousValue = this._tbl_departamento.Entity;
				if (((previousValue != value) 
							|| (this._tbl_departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_departamento.Entity = null;
						previousValue.tbl_empleados.Remove(this);
					}
					this._tbl_departamento.Entity = value;
					if ((value != null))
					{
						value.tbl_empleados.Add(this);
						this._id_departamento = value.id_departamento;
					}
					else
					{
						this._id_departamento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_departamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_cargo_tbl_empleado", Storage="_tbl_cargo", ThisKey="id_cargos", OtherKey="id_cargos", IsForeignKey=true)]
		public tbl_cargo tbl_cargo
		{
			get
			{
				return this._tbl_cargo.Entity;
			}
			set
			{
				tbl_cargo previousValue = this._tbl_cargo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_cargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_cargo.Entity = null;
						previousValue.tbl_empleados.Remove(this);
					}
					this._tbl_cargo.Entity = value;
					if ((value != null))
					{
						value.tbl_empleados.Add(this);
						this._id_cargos = value.id_cargos;
					}
					else
					{
						this._id_cargos = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_cargo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_capacitacions(tbl_capacitacion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = this;
		}
		
		private void detach_tbl_capacitacions(tbl_capacitacion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = null;
		}
		
		private void attach_tbl_familiars(tbl_familiar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = this;
		}
		
		private void detach_tbl_familiars(tbl_familiar entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = null;
		}
		
		private void attach_tbl_referencias(tbl_referencia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = this;
		}
		
		private void detach_tbl_referencias(tbl_referencia entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_empresa")]
	public partial class tbl_empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_empresa;
		
		private string _ruc_empresa;
		
		private string _nombre_empresa;
		
		private string _direccion_empresa;
		
		private string _telefono_empresa;
		
		private System.DateTime _fecha_empresa;
		
		private char _estado_empresa;
		
		private EntitySet<tbl_departamento> _tbl_departamentos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_empresaChanging(int value);
    partial void Onid_empresaChanged();
    partial void Onruc_empresaChanging(string value);
    partial void Onruc_empresaChanged();
    partial void Onnombre_empresaChanging(string value);
    partial void Onnombre_empresaChanged();
    partial void Ondireccion_empresaChanging(string value);
    partial void Ondireccion_empresaChanged();
    partial void Ontelefono_empresaChanging(string value);
    partial void Ontelefono_empresaChanged();
    partial void Onfecha_empresaChanging(System.DateTime value);
    partial void Onfecha_empresaChanged();
    partial void Onestado_empresaChanging(char value);
    partial void Onestado_empresaChanged();
    #endregion
		
		public tbl_empresa()
		{
			this._tbl_departamentos = new EntitySet<tbl_departamento>(new Action<tbl_departamento>(this.attach_tbl_departamentos), new Action<tbl_departamento>(this.detach_tbl_departamentos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empresa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_empresa
		{
			get
			{
				return this._id_empresa;
			}
			set
			{
				if ((this._id_empresa != value))
				{
					this.Onid_empresaChanging(value);
					this.SendPropertyChanging();
					this._id_empresa = value;
					this.SendPropertyChanged("id_empresa");
					this.Onid_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ruc_empresa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ruc_empresa
		{
			get
			{
				return this._ruc_empresa;
			}
			set
			{
				if ((this._ruc_empresa != value))
				{
					this.Onruc_empresaChanging(value);
					this.SendPropertyChanging();
					this._ruc_empresa = value;
					this.SendPropertyChanged("ruc_empresa");
					this.Onruc_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_empresa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_empresa
		{
			get
			{
				return this._nombre_empresa;
			}
			set
			{
				if ((this._nombre_empresa != value))
				{
					this.Onnombre_empresaChanging(value);
					this.SendPropertyChanging();
					this._nombre_empresa = value;
					this.SendPropertyChanged("nombre_empresa");
					this.Onnombre_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_empresa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion_empresa
		{
			get
			{
				return this._direccion_empresa;
			}
			set
			{
				if ((this._direccion_empresa != value))
				{
					this.Ondireccion_empresaChanging(value);
					this.SendPropertyChanging();
					this._direccion_empresa = value;
					this.SendPropertyChanged("direccion_empresa");
					this.Ondireccion_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_empresa", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefono_empresa
		{
			get
			{
				return this._telefono_empresa;
			}
			set
			{
				if ((this._telefono_empresa != value))
				{
					this.Ontelefono_empresaChanging(value);
					this.SendPropertyChanging();
					this._telefono_empresa = value;
					this.SendPropertyChanged("telefono_empresa");
					this.Ontelefono_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_empresa", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_empresa
		{
			get
			{
				return this._fecha_empresa;
			}
			set
			{
				if ((this._fecha_empresa != value))
				{
					this.Onfecha_empresaChanging(value);
					this.SendPropertyChanging();
					this._fecha_empresa = value;
					this.SendPropertyChanged("fecha_empresa");
					this.Onfecha_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_empresa", DbType="Char(1) NOT NULL")]
		public char estado_empresa
		{
			get
			{
				return this._estado_empresa;
			}
			set
			{
				if ((this._estado_empresa != value))
				{
					this.Onestado_empresaChanging(value);
					this.SendPropertyChanging();
					this._estado_empresa = value;
					this.SendPropertyChanged("estado_empresa");
					this.Onestado_empresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empresa_tbl_departamento", Storage="_tbl_departamentos", ThisKey="id_empresa", OtherKey="id_empresa")]
		public EntitySet<tbl_departamento> tbl_departamentos
		{
			get
			{
				return this._tbl_departamentos;
			}
			set
			{
				this._tbl_departamentos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_departamentos(tbl_departamento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empresa = this;
		}
		
		private void detach_tbl_departamentos(tbl_departamento entity)
		{
			this.SendPropertyChanging();
			entity.tbl_empresa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_familiar")]
	public partial class tbl_familiar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_familiar;
		
		private string _nombres_familiar;
		
		private string _dni_familiar;
		
		private string _direccion_familiar;
		
		private string _telefono_familiar;
		
		private System.DateTime _fecha_familiar;
		
		private char _estado_familiar;
		
		private System.Nullable<int> _id_empleado;
		
		private EntityRef<tbl_empleado> _tbl_empleado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_familiarChanging(int value);
    partial void Onid_familiarChanged();
    partial void Onnombres_familiarChanging(string value);
    partial void Onnombres_familiarChanged();
    partial void Ondni_familiarChanging(string value);
    partial void Ondni_familiarChanged();
    partial void Ondireccion_familiarChanging(string value);
    partial void Ondireccion_familiarChanged();
    partial void Ontelefono_familiarChanging(string value);
    partial void Ontelefono_familiarChanged();
    partial void Onfecha_familiarChanging(System.DateTime value);
    partial void Onfecha_familiarChanged();
    partial void Onestado_familiarChanging(char value);
    partial void Onestado_familiarChanged();
    partial void Onid_empleadoChanging(System.Nullable<int> value);
    partial void Onid_empleadoChanged();
    #endregion
		
		public tbl_familiar()
		{
			this._tbl_empleado = default(EntityRef<tbl_empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_familiar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_familiar
		{
			get
			{
				return this._id_familiar;
			}
			set
			{
				if ((this._id_familiar != value))
				{
					this.Onid_familiarChanging(value);
					this.SendPropertyChanging();
					this._id_familiar = value;
					this.SendPropertyChanged("id_familiar");
					this.Onid_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_familiar", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_familiar
		{
			get
			{
				return this._nombres_familiar;
			}
			set
			{
				if ((this._nombres_familiar != value))
				{
					this.Onnombres_familiarChanging(value);
					this.SendPropertyChanging();
					this._nombres_familiar = value;
					this.SendPropertyChanged("nombres_familiar");
					this.Onnombres_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_familiar", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string dni_familiar
		{
			get
			{
				return this._dni_familiar;
			}
			set
			{
				if ((this._dni_familiar != value))
				{
					this.Ondni_familiarChanging(value);
					this.SendPropertyChanging();
					this._dni_familiar = value;
					this.SendPropertyChanged("dni_familiar");
					this.Ondni_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_familiar", DbType="VarChar(100)")]
		public string direccion_familiar
		{
			get
			{
				return this._direccion_familiar;
			}
			set
			{
				if ((this._direccion_familiar != value))
				{
					this.Ondireccion_familiarChanging(value);
					this.SendPropertyChanging();
					this._direccion_familiar = value;
					this.SendPropertyChanged("direccion_familiar");
					this.Ondireccion_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_familiar", DbType="VarChar(10)")]
		public string telefono_familiar
		{
			get
			{
				return this._telefono_familiar;
			}
			set
			{
				if ((this._telefono_familiar != value))
				{
					this.Ontelefono_familiarChanging(value);
					this.SendPropertyChanging();
					this._telefono_familiar = value;
					this.SendPropertyChanged("telefono_familiar");
					this.Ontelefono_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_familiar", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_familiar
		{
			get
			{
				return this._fecha_familiar;
			}
			set
			{
				if ((this._fecha_familiar != value))
				{
					this.Onfecha_familiarChanging(value);
					this.SendPropertyChanging();
					this._fecha_familiar = value;
					this.SendPropertyChanged("fecha_familiar");
					this.Onfecha_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_familiar", DbType="Char(1) NOT NULL")]
		public char estado_familiar
		{
			get
			{
				return this._estado_familiar;
			}
			set
			{
				if ((this._estado_familiar != value))
				{
					this.Onestado_familiarChanging(value);
					this.SendPropertyChanging();
					this._estado_familiar = value;
					this.SendPropertyChanged("estado_familiar");
					this.Onestado_familiarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="Int")]
		public System.Nullable<int> id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					if (this._tbl_empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_familiar", Storage="_tbl_empleado", ThisKey="id_empleado", OtherKey="id_empleado", IsForeignKey=true)]
		public tbl_empleado tbl_empleado
		{
			get
			{
				return this._tbl_empleado.Entity;
			}
			set
			{
				tbl_empleado previousValue = this._tbl_empleado.Entity;
				if (((previousValue != value) 
							|| (this._tbl_empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_empleado.Entity = null;
						previousValue.tbl_familiars.Remove(this);
					}
					this._tbl_empleado.Entity = value;
					if ((value != null))
					{
						value.tbl_familiars.Add(this);
						this._id_empleado = value.id_empleado;
					}
					else
					{
						this._id_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_referencias")]
	public partial class tbl_referencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_referencias;
		
		private string _nombres_referencias;
		
		private string _dni_referencias;
		
		private string _telefono_referencias;
		
		private System.DateTime _fecha_referencias;
		
		private char _estado_referencias;
		
		private System.Nullable<int> _id_empleado;
		
		private EntityRef<tbl_empleado> _tbl_empleado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_referenciasChanging(int value);
    partial void Onid_referenciasChanged();
    partial void Onnombres_referenciasChanging(string value);
    partial void Onnombres_referenciasChanged();
    partial void Ondni_referenciasChanging(string value);
    partial void Ondni_referenciasChanged();
    partial void Ontelefono_referenciasChanging(string value);
    partial void Ontelefono_referenciasChanged();
    partial void Onfecha_referenciasChanging(System.DateTime value);
    partial void Onfecha_referenciasChanged();
    partial void Onestado_referenciasChanging(char value);
    partial void Onestado_referenciasChanged();
    partial void Onid_empleadoChanging(System.Nullable<int> value);
    partial void Onid_empleadoChanged();
    #endregion
		
		public tbl_referencia()
		{
			this._tbl_empleado = default(EntityRef<tbl_empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_referencias", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_referencias
		{
			get
			{
				return this._id_referencias;
			}
			set
			{
				if ((this._id_referencias != value))
				{
					this.Onid_referenciasChanging(value);
					this.SendPropertyChanging();
					this._id_referencias = value;
					this.SendPropertyChanged("id_referencias");
					this.Onid_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres_referencias", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombres_referencias
		{
			get
			{
				return this._nombres_referencias;
			}
			set
			{
				if ((this._nombres_referencias != value))
				{
					this.Onnombres_referenciasChanging(value);
					this.SendPropertyChanging();
					this._nombres_referencias = value;
					this.SendPropertyChanged("nombres_referencias");
					this.Onnombres_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dni_referencias", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string dni_referencias
		{
			get
			{
				return this._dni_referencias;
			}
			set
			{
				if ((this._dni_referencias != value))
				{
					this.Ondni_referenciasChanging(value);
					this.SendPropertyChanging();
					this._dni_referencias = value;
					this.SendPropertyChanged("dni_referencias");
					this.Ondni_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_referencias", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefono_referencias
		{
			get
			{
				return this._telefono_referencias;
			}
			set
			{
				if ((this._telefono_referencias != value))
				{
					this.Ontelefono_referenciasChanging(value);
					this.SendPropertyChanging();
					this._telefono_referencias = value;
					this.SendPropertyChanged("telefono_referencias");
					this.Ontelefono_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_referencias", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_referencias
		{
			get
			{
				return this._fecha_referencias;
			}
			set
			{
				if ((this._fecha_referencias != value))
				{
					this.Onfecha_referenciasChanging(value);
					this.SendPropertyChanging();
					this._fecha_referencias = value;
					this.SendPropertyChanged("fecha_referencias");
					this.Onfecha_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_referencias", DbType="Char(1) NOT NULL")]
		public char estado_referencias
		{
			get
			{
				return this._estado_referencias;
			}
			set
			{
				if ((this._estado_referencias != value))
				{
					this.Onestado_referenciasChanging(value);
					this.SendPropertyChanging();
					this._estado_referencias = value;
					this.SendPropertyChanged("estado_referencias");
					this.Onestado_referenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="Int")]
		public System.Nullable<int> id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					if (this._tbl_empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_empleado_tbl_referencia", Storage="_tbl_empleado", ThisKey="id_empleado", OtherKey="id_empleado", IsForeignKey=true)]
		public tbl_empleado tbl_empleado
		{
			get
			{
				return this._tbl_empleado.Entity;
			}
			set
			{
				tbl_empleado previousValue = this._tbl_empleado.Entity;
				if (((previousValue != value) 
							|| (this._tbl_empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_empleado.Entity = null;
						previousValue.tbl_referencias.Remove(this);
					}
					this._tbl_empleado.Entity = value;
					if ((value != null))
					{
						value.tbl_referencias.Add(this);
						this._id_empleado = value.id_empleado;
					}
					else
					{
						this._id_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_rol")]
	public partial class tbl_rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rol;
		
		private string _descripcion_rol;
		
		private System.DateTime _fecha_rol;
		
		private char _estado_rol;
		
		private EntitySet<tbl_usuario> _tbl_usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rolChanging(int value);
    partial void Onid_rolChanged();
    partial void Ondescripcion_rolChanging(string value);
    partial void Ondescripcion_rolChanged();
    partial void Onfecha_rolChanging(System.DateTime value);
    partial void Onfecha_rolChanged();
    partial void Onestado_rolChanging(char value);
    partial void Onestado_rolChanged();
    #endregion
		
		public tbl_rol()
		{
			this._tbl_usuarios = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuarios), new Action<tbl_usuario>(this.detach_tbl_usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rol", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_rol
		{
			get
			{
				return this._id_rol;
			}
			set
			{
				if ((this._id_rol != value))
				{
					this.Onid_rolChanging(value);
					this.SendPropertyChanging();
					this._id_rol = value;
					this.SendPropertyChanged("id_rol");
					this.Onid_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_rol", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string descripcion_rol
		{
			get
			{
				return this._descripcion_rol;
			}
			set
			{
				if ((this._descripcion_rol != value))
				{
					this.Ondescripcion_rolChanging(value);
					this.SendPropertyChanging();
					this._descripcion_rol = value;
					this.SendPropertyChanged("descripcion_rol");
					this.Ondescripcion_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_rol", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_rol
		{
			get
			{
				return this._fecha_rol;
			}
			set
			{
				if ((this._fecha_rol != value))
				{
					this.Onfecha_rolChanging(value);
					this.SendPropertyChanging();
					this._fecha_rol = value;
					this.SendPropertyChanged("fecha_rol");
					this.Onfecha_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_rol", DbType="Char(1) NOT NULL")]
		public char estado_rol
		{
			get
			{
				return this._estado_rol;
			}
			set
			{
				if ((this._estado_rol != value))
				{
					this.Onestado_rolChanging(value);
					this.SendPropertyChanging();
					this._estado_rol = value;
					this.SendPropertyChanged("estado_rol");
					this.Onestado_rolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_rol_tbl_usuario", Storage="_tbl_usuarios", ThisKey="id_rol", OtherKey="id_rol")]
		public EntitySet<tbl_usuario> tbl_usuarios
		{
			get
			{
				return this._tbl_usuarios;
			}
			set
			{
				this._tbl_usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuarios(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = this;
		}
		
		private void detach_tbl_usuarios(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_rol = null;
		}
	}
}
#pragma warning restore 1591
